### ISSUE TITLE
SpineAnimationBuilder打开后白屏无法运行

### ISSUE THREAD

**Issue by liuabin** [Goodjooy/SpineAnimationBuilder#1]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/F:/char/AnimationBuilder_jar/lwjgl-2.9.2.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Goodjooy** [comment]
稍微查了一下，似乎是版本问题，你可能用的是1.9,1.10的，而且warn并不会终止运行。
使用 Ctrl＋l 也无响应么

**Comment by liuabin** [comment]
> 稍微查了一下，似乎是版本问题，你可能用的是1.9,1.10的，而且warn并不会终止运行。
> 使用 Ctrl＋l 也无响应么

是JAVA 11 LTS...
^I 是什么快捷键并没有反应

**Comment by liuabin** [comment]
a看到快捷键的说明了，不过并没有什么反应

**Comment by Goodjooy** [comment]
CTRL+L

**Comment by Goodjooy** [comment]
要不你试试看jre1.8

**Comment by liuabin** [comment]
换成jre8后依然白屏，不过Ctrl+L确实有窗口弹出
F:\char\jre1.8.0_201\bin>java.exe -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by Goodjooy** [comment]
弹出的是选择skel文件的，找一个skel文件打开试试看有没有反应，如果加载成功控制台会有东西的
